import { GOOGLE_MAPS_API_KEY } from '@env';

export const API_CONFIG = {
  GOOGLE_MAPS_API_KEY: GOOGLE_MAPS_API_KEY || 'AIzaSyBOwNDFwx9EerTB29GCdwyCyaaQIDgs9UI',
  GOOGLE_PLACES_API_KEY: GOOGLE_MAPS_API_KEY || 'AIzaSyBOwNDFwx9EerTB29GCdwyCyaaQIDgs9UI',
  GOOGLE_DIRECTIONS_API_KEY: GOOGLE_MAPS_API_KEY || 'AIzaSyBOwNDFwx9EerTB29GCdwyCyaaQIDgs9UI',
};

export const BACKEND_URL = 'http://localhost:3000';
